//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_levelconfig.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelConfig")]
  public partial class LevelConfig : global::ProtoBuf.IExtensible
  {
    public LevelConfig() {}
    
    private uint _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _LevelResID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LevelResID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelResID
    {
      get { return _LevelResID; }
      set { _LevelResID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelConfigArray")]
  public partial class LevelConfigArray : global::ProtoBuf.IExtensible
  {
    public LevelConfigArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.LevelConfig> _items = new global::System.Collections.Generic.List<dataconfig.LevelConfig>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.LevelConfig> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}