//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_npcmissionfenbao.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NPCMissionFenBao")]
  public partial class NPCMissionFenBao : global::ProtoBuf.IExtensible
  {
    public NPCMissionFenBao() {}
    
    private uint _TaskID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TaskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TaskID
    {
      get { return _TaskID; }
      set { _TaskID = value; }
    }
    private uint _Pakage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Pakage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Pakage
    {
      get { return _Pakage; }
      set { _Pakage = value; }
    }
    private uint _Version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NPCMissionFenBaoArray")]
  public partial class NPCMissionFenBaoArray : global::ProtoBuf.IExtensible
  {
    public NPCMissionFenBaoArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.NPCMissionFenBao> _items = new global::System.Collections.Generic.List<dataconfig.NPCMissionFenBao>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.NPCMissionFenBao> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}