//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_luafenbao.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LuaFenBao")]
  public partial class LuaFenBao : global::ProtoBuf.IExtensible
  {
    public LuaFenBao() {}
    
    private string _AbName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AbName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AbName
    {
      get { return _AbName; }
      set { _AbName = value; }
    }
    private uint _Pakage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Pakage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Pakage
    {
      get { return _Pakage; }
      set { _Pakage = value; }
    }
    private uint _Version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LuaFenBaoArray")]
  public partial class LuaFenBaoArray : global::ProtoBuf.IExtensible
  {
    public LuaFenBaoArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.LuaFenBao> _items = new global::System.Collections.Generic.List<dataconfig.LuaFenBao>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.LuaFenBao> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}