//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_taskinfo.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfo")]
  public partial class TaskInfo : global::ProtoBuf.IExtensible
  {
    public TaskInfo() {}
    
    private uint _TaskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TaskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TaskId
    {
      get { return _TaskId; }
      set { _TaskId = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Desc = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    private uint _NPCID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"NPCID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NPCID
    {
      get { return _NPCID; }
      set { _NPCID = value; }
    }
    private uint _MusicResID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"MusicResID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MusicResID
    {
      get { return _MusicResID; }
      set { _MusicResID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfoArray")]
  public partial class TaskInfoArray : global::ProtoBuf.IExtensible
  {
    public TaskInfoArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.TaskInfo> _items = new global::System.Collections.Generic.List<dataconfig.TaskInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.TaskInfo> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}