//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_scenefenbao.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SceneFenBao")]
  public partial class SceneFenBao : global::ProtoBuf.IExtensible
  {
    public SceneFenBao() {}
    
    private uint _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private uint _Pakage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Pakage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Pakage
    {
      get { return _Pakage; }
      set { _Pakage = value; }
    }
    private uint _Version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SceneFenBaoArray")]
  public partial class SceneFenBaoArray : global::ProtoBuf.IExtensible
  {
    public SceneFenBaoArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.SceneFenBao> _items = new global::System.Collections.Generic.List<dataconfig.SceneFenBao>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.SceneFenBao> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}