//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dataconfig_npcfenbao.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NpcFenBao")]
  public partial class NpcFenBao : global::ProtoBuf.IExtensible
  {
    public NpcFenBao() {}
    
    private uint _ResID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ResID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ResID
    {
      get { return _ResID; }
      set { _ResID = value; }
    }
    private uint _Pakage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Pakage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Pakage
    {
      get { return _Pakage; }
      set { _Pakage = value; }
    }
    private uint _Version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NpcFenBaoArray")]
  public partial class NpcFenBaoArray : global::ProtoBuf.IExtensible
  {
    public NpcFenBaoArray() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.NpcFenBao> _items = new global::System.Collections.Generic.List<dataconfig.NpcFenBao>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.NpcFenBao> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}