-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('cs_honor_pb')


local CSUPDATEHONORREQ = protobuf.Descriptor();
local CSUPDATEHONORRES = protobuf.Descriptor();
local CSUPDATEHONORRES_RETCODE_FIELD = protobuf.FieldDescriptor();

CSUPDATEHONORREQ.name = "CSUpdateHonorReq"
CSUPDATEHONORREQ.full_name = ".cs.CSUpdateHonorReq"
CSUPDATEHONORREQ.nested_types = {}
CSUPDATEHONORREQ.enum_types = {}
CSUPDATEHONORREQ.fields = {}
CSUPDATEHONORREQ.is_extendable = false
CSUPDATEHONORREQ.extensions = {}
CSUPDATEHONORRES_RETCODE_FIELD.name = "RetCode"
CSUPDATEHONORRES_RETCODE_FIELD.full_name = ".cs.CSUpdateHonorRes.RetCode"
CSUPDATEHONORRES_RETCODE_FIELD.number = 1
CSUPDATEHONORRES_RETCODE_FIELD.index = 0
CSUPDATEHONORRES_RETCODE_FIELD.label = 2
CSUPDATEHONORRES_RETCODE_FIELD.has_default_value = false
CSUPDATEHONORRES_RETCODE_FIELD.default_value = 0
CSUPDATEHONORRES_RETCODE_FIELD.type = 5
CSUPDATEHONORRES_RETCODE_FIELD.cpp_type = 1

CSUPDATEHONORRES.name = "CSUpdateHonorRes"
CSUPDATEHONORRES.full_name = ".cs.CSUpdateHonorRes"
CSUPDATEHONORRES.nested_types = {}
CSUPDATEHONORRES.enum_types = {}
CSUPDATEHONORRES.fields = {CSUPDATEHONORRES_RETCODE_FIELD}
CSUPDATEHONORRES.is_extendable = false
CSUPDATEHONORRES.extensions = {}

CSUpdateHonorReq = protobuf.Message(CSUPDATEHONORREQ)
CSUpdateHonorRes = protobuf.Message(CSUPDATEHONORRES)

