-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('cs_poll_pb')


local CSPOLLREQ = protobuf.Descriptor();
local CSPOLLRES = protobuf.Descriptor();
local CSPOLLRES_RETCODE_FIELD = protobuf.FieldDescriptor();

CSPOLLREQ.name = "CSPollReq"
CSPOLLREQ.full_name = ".cs.CSPollReq"
CSPOLLREQ.nested_types = {}
CSPOLLREQ.enum_types = {}
CSPOLLREQ.fields = {}
CSPOLLREQ.is_extendable = false
CSPOLLREQ.extensions = {}
CSPOLLRES_RETCODE_FIELD.name = "RetCode"
CSPOLLRES_RETCODE_FIELD.full_name = ".cs.CSPollRes.RetCode"
CSPOLLRES_RETCODE_FIELD.number = 1
CSPOLLRES_RETCODE_FIELD.index = 0
CSPOLLRES_RETCODE_FIELD.label = 2
CSPOLLRES_RETCODE_FIELD.has_default_value = false
CSPOLLRES_RETCODE_FIELD.default_value = 0
CSPOLLRES_RETCODE_FIELD.type = 5
CSPOLLRES_RETCODE_FIELD.cpp_type = 1

CSPOLLRES.name = "CSPollRes"
CSPOLLRES.full_name = ".cs.CSPollRes"
CSPOLLRES.nested_types = {}
CSPOLLRES.enum_types = {}
CSPOLLRES.fields = {CSPOLLRES_RETCODE_FIELD}
CSPOLLRES.is_extendable = false
CSPOLLRES.extensions = {}

CSPollReq = protobuf.Message(CSPOLLREQ)
CSPollRes = protobuf.Message(CSPOLLRES)

