-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('cs_questionaire_pb')


local CSQUESTIONAIREREQ = protobuf.Descriptor();
local CSQUESTIONAIRERES = protobuf.Descriptor();
local CSQUESTIONAIRERES_RETCODE_FIELD = protobuf.FieldDescriptor();

CSQUESTIONAIREREQ.name = "CSQuestionaireReq"
CSQUESTIONAIREREQ.full_name = ".cs.CSQuestionaireReq"
CSQUESTIONAIREREQ.nested_types = {}
CSQUESTIONAIREREQ.enum_types = {}
CSQUESTIONAIREREQ.fields = {}
CSQUESTIONAIREREQ.is_extendable = false
CSQUESTIONAIREREQ.extensions = {}
CSQUESTIONAIRERES_RETCODE_FIELD.name = "RetCode"
CSQUESTIONAIRERES_RETCODE_FIELD.full_name = ".cs.CSQuestionaireRes.RetCode"
CSQUESTIONAIRERES_RETCODE_FIELD.number = 1
CSQUESTIONAIRERES_RETCODE_FIELD.index = 0
CSQUESTIONAIRERES_RETCODE_FIELD.label = 2
CSQUESTIONAIRERES_RETCODE_FIELD.has_default_value = false
CSQUESTIONAIRERES_RETCODE_FIELD.default_value = 0
CSQUESTIONAIRERES_RETCODE_FIELD.type = 5
CSQUESTIONAIRERES_RETCODE_FIELD.cpp_type = 1

CSQUESTIONAIRERES.name = "CSQuestionaireRes"
CSQUESTIONAIRERES.full_name = ".cs.CSQuestionaireRes"
CSQUESTIONAIRERES.nested_types = {}
CSQUESTIONAIRERES.enum_types = {}
CSQUESTIONAIRERES.fields = {CSQUESTIONAIRERES_RETCODE_FIELD}
CSQUESTIONAIRERES.is_extendable = false
CSQUESTIONAIRERES.extensions = {}

CSQuestionaireReq = protobuf.Message(CSQUESTIONAIREREQ)
CSQuestionaireRes = protobuf.Message(CSQUESTIONAIRERES)

